services:
  ollama:
    image: ollama/ollama:latest
    environment:
      OLLAMA_DEBUG: "1"
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      MODELS: ${MODELS}
      PRE_PROCESSING_MODEL: ${PRE_PROCESSING_MODEL}
    ports:
      - "11435:11434"
    gpus: all
    entrypoint:
      - /bin/sh
      - -c
      - |
        . /scripts/load_ollama_env.sh
        exec /scripts/ollama_init.sh
    volumes:
    - ./scripts:/scripts:ro # can make a custom image instead
    - /data2/nkhajehn/ollama:/root/.ollama
    - ./.env:/app/.env:ro
    restart: unless-stopped

  watcher:
    image: my-haiku-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: watcher
    working_dir: /app
    volumes:
      - ./.env:/app/.env:ro
      - ./docling_models:/root/.cache/huggingface
      - ./raw_docs:/raw_docs
      - ./docs_processed:/docs_processed
      - ./data:/data
      #- ./haiku.rag.yaml:/app/haiku.rag.yaml:ro
    environment:
      PYTHONPATH: /app
      CONFIG: /app/haiku.rag.yaml
      DB_PATH: /data/haiku.rag.lancedb
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      #MODELS: ${MODELS}
      PRE_PROCESSING_MODEL: ${PRE_PROCESSING_MODEL}
      DOCLING_SERVE_URL: ${DOCLING_SERVE_URL}
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    depends_on:
      - docling-serve
      - ollama
    restart: unless-stopped

  haiku-monitor:
    image: my-haiku-app:latest
    working_dir: /app
    entrypoint: ["/bin/sh", "/app/scripts/haiku_monitor_entrypoint.sh"]
    volumes:
      - ./docs_processed:/docs_processed
      - ./data:/data
      - ./.env:/app/.env:ro
      #- ./haiku.rag.yaml:/app/haiku.rag.yaml:ro
    environment:
      DOCLING_SERVE_URL: http://docling-serve:5001
      PYTHONPATH: /app
      CONFIG: /app/haiku.rag.yaml
      DB_PATH: /data/haiku.rag.lancedb
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
    depends_on:
      - docling-serve
      - watcher
    restart: unless-stopped

  orchestrator:
    image: my-orchestrator-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: orchestrator
    working_dir: /app
    environment:
      OLLAMA_DEBUG: "1"
      PYTHONPATH: /app
      DB_PATH: /data/haiku.rag.lancedb
      CONFIG: /app/haiku.rag.yaml
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      MODELS: ${MODELS}
      PRE_PROCESSING_MODEL: ${PRE_PROCESSING_MODEL}
      DOCLING_SERVE_URL: ${DOCLING_SERVE_URL}
      HAIKU_EMBEDDING_MODEL: "nomic-embed-text:latest"
      HAIKU_EMBEDDING_VECTOR_DIM: "768"
    ports:
      - "8002:8002"
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/data
      - ./.env:/app/.env:ro
      #- ./haiku.rag.yaml:/app/haiku.rag.yaml:ro
      - ./llm_pipeline/prompts:/app/llm_pipeline/prompts
    depends_on:
      - ollama

  docling-serve:
    image: ghcr.io/docling-project/docling-serve:latest
    restart: unless-stopped
    ports:
      - "5001:5001"
    #volumes:
    #  - /data2/nkhajehn/docling_tmp:/tmp
